[package]
name = "gbc"
version = "0.1.0"
authors = ["alloncm <alloncm@gmail.com>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib_gbc = {path = "../lib_gbc/"}
stupid_gfx = {path = "../stupid_gfx/"}